### ISSUE TITLE
cannot run donejs-chat with donejs start

### ISSUE THREAD

**Issue by marekbialkowski** [donejs/chat#15]
I:\donejs_new\donejs-chat>donejs start

> donejs-chat@0.0.0 start I:\donejs_new\donejs-chat
> can-serve --port 8080

can-serve starting on http://localhost:8080
{ [Error: Error loading "can/view/stache/stache" at file:I:/donejs_new/donejs-chat/can/view/stache/stache.js
Error loading "can/view/stache/stache" from "@ssr/plugins/canjs" at file:I:/donejs_new/donejs-chat/node_modules/can-ssr/lib/plugins/canjs.js
ENOENT: no such file or directory, open 'I:\donejs_new\donejs-chat\can\view\stache\stache\index.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'I:\\donejs_new\\donejs-chat\\can\\view\\stache\\stache\\index.js' }
Potentially unhandled rejection [8] TypeError: Cannot read property 'importPromise' of undefined
    at getMainModule (I:\donejs_new\donejs-chat\node_modules\can-ssr\lib\index.js:29:14)
    at I:\donejs_new\donejs-chat\node_modules\can-ssr\lib\index.js:43:10
    at tryCatchReject (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist\e
s6-module-loader.src.js:1183:30)
    at runContinuation1 (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist
\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist\e
s6-module-loader.src.js:930:4)
    at Pending.run (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist\es6-
module-loader.src.js:821:13)
    at Scheduler._drain (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist
\es6-module-loader.src.js:97:19)
    at Scheduler.drain (I:\donejs_new\donejs-chat\node_modules\can-ssr\node_modules\steal\node_modules\steal-systemjs\node_modules\steal-es6-module-loader\dist\
es6-module-loader.src.js:62:9)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)

**Comment by matthewp** [comment]
Thanks, going to take a look, might be an outdated version.

**Comment by matthewp** [comment]
Hey @marekbialkowski, I've updated the project to DoneJS 0.7.0, it should be working now, let me know if you have any issues and I'll reopen it.
